services:
  database:
    container_name: database
    build: requirements/mariadb
    image: mariadb:inception
    ports:
      - "3306:3306"
    networks:
      - inception-network
    environment:
      - "MYSQL_ROOT_PW=${DB_ROOT_PW}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_USER_PW=${DB_USER_PW}"
      - "MYSQL_DB_NAME=${DB_NAME}"
    volumes:
      - "db_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  server:
    container_name: nginx_serv
    build: requirements/nginx
    image: nginx:inception
    ports:
      - "443:443"
    networks:
      - inception-network
    depends_on:
      - wordpress
    volumes:
      - "wp_data:/var/www/html"

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress:inception
    ports:
      - "9000:9000"
    networks:
      - inception-network
    environment:
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_USER_PW=${DB_USER_PW}"
      - "MYSQL_DB_NAME=${DB_NAME}"
      - "MYSQL_HOST=${DB_HOSTNAME}"
      - "WP_URL=${WP_URL}"
      - "WP_TITLE=${WP_TITLE}"
      - "WP_ADMIN=${WP_ADMIN}"
      - "WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}"
      - "WP_ADMIN_PW=${WP_ADMIN_PW}"
      - "WP_USER=${WP_USER}"
      - "WP_USER_EMAIL=${WP_USER_EMAIL}"
      - "WP_USER_PW=${WP_USER_PW}"
    volumes:
      - "wp_data:/var/www/html"
    depends_on:
      database:
        condition: service_healthy

networks:
  inception-network:

volumes:
  db_data:
    driver_opts:
      device: /home/mchibane/data/mysql
      o: bind
      type: none
  wp_data:
    driver_opts:
      device: /home/mchibane/data/wordpress
      o: bind
      type: none
