FROM debian:buster

RUN apt update -y && apt install -y mariadb-server
#&& rm -rf /var/lib/apt/lists/* \
#&& mkdir -p /var/run/mysqld \
#&& chown -R mysql:mysql /var/run/mysqld \
#&& chmod 777 /var/run/mysqld

CMD bash
